return {
	{ x = 0, y = 0, anchorX = 0, anchorY = 0, name = "TopLeft" },
	{ x = 1, y = 0, anchorX = 1, anchorY = 0, name = "TopRight" },
	{ x = 0, y = 1, anchorX = 0, anchorY = 1, name = "BottomLeft" },
	{ x = 1, y = 1, anchorX = 1, anchorY = 1, name = "BottomRight" },
	{ x = 0.5, y = 0, anchorX = 0.5, anchorY = 0, name = "TopMiddle" },
	{ x = 0.5, y = 1, anchorX = 0.5, anchorY = 1, name = "BottomMiddle" },
	{ x = 0, y = 0.5, anchorX = 0, anchorY = 0.5, name = "LeftMiddle" },
	{ x = 1, y = 0.5, anchorX = 1, anchorY = 0.5, name = "RightMiddle" },
}
